routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('home');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['auth']], function(){
	Route::resource('news', 'News');
	Route::post('news/getNews', 'News@getNews')->name('news.getNews');
	Route::get('news/{news}/status', 'News@status')->name('news.status');

	Route::resource('users', 'Users');
	Route::post('users/getUsers', 'Users@getUsers')->name('users.getUsers');
	Route::get('users/{user}/status', 'Users@status')->name('users.status');
});

app/Models/News.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;

use App\User;

class News extends Model implements HasMedia
{
    use InteractsWithMedia;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'user_id', 'title', 'description', 'keywords', 'is_approved',
    ];

    public function registerMediaCollections(): void {
        $this->addMediaCollection('image')
             ->singleFile();
    }

    /**
     * Get the user of the news.
     */
    public function user(){
        return $this->belongsTo(User::class)->withDefault();
    }
}

app/Http/Controllers/News.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\News as NewsModel;

use DataTables;
use Form;

class News extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('news.index');
    }

     /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function getNews(Request $request){
        if(auth()->user()->hasRole(config('constants.ROLE_TYPE_SUPERADMIN')))
            $news = NewsModel::query()->with(['user']);
        else
            $news = NewsModel::query()->with(['user'])->where('user_id', auth()->id());

        return DataTables::of($news)
            ->editColumn('created_at', function($news){
                return date(config('constants.DATETIME_FORMAT'), strtotime($news->created_at));
            })
            ->filterColumn('created_at', function ($query, $keyword) {
                $keyword = strtolower($keyword);
                $query->whereRaw("LOWER(DATE_FORMAT(created_at,'".config('constants.MYSQL_DATETIME_FORMAT')."')) like ?", ["%$keyword%"]);
            })
            ->editColumn('keywords', function($news){
                return implode(', ', explode(',', $news->keywords));
            })
            ->editColumn('is_approved', function ($news) {
                if($news->is_approved == TRUE ){
                    if(auth()->user()->hasRole(config('constants.ROLE_TYPE_SUPERADMIN')))
                        return "<a href='".route('news.status',$news)."'><span class='badge badge-success'>Yes</span></a>";
                    else
                        return "<span class='badge badge-success'>Yes</span>";
                }else{
                    if(auth()->user()->hasRole(config('constants.ROLE_TYPE_SUPERADMIN')))
                        return "<a href='".route('news.status',$news)."'><span class='badge badge-danger'>No</span></a>";
                    else
                        return "<span class='badge badge-danger'>No</span>";

                }
            })
            ->addColumn('actions', function ($news) {
                return
                        // Edit
                        '<a href="'.route('news.edit',[$news->id]).'" class="btn btn-primary">Edit</a> '.
                        // Delete
                        Form::open(array(
                          'style' => 'display: inline-block;',
                          'method' => 'DELETE',
                           'onsubmit'=>"return confirm('Do you really want to delete?')",
                          'route' => ['news.destroy', $news->id])).
                        ' <button type="submit" class="btn btn-danger">Delete</button>'.
                        Form::close();
            })
            ->rawColumns(['is_approved','actions'])
            ->make(true);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('news.form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'title' => 'required|unique:news',
            'description' => 'required',
            'image'=>[
                'file',
                'image',
                'max:'.(config('media-library.max_file_size') / 1024),
            ],
            'keywords' => [
                'required',
                function ($attribute, $keywords, $fail) {
                    if (count(explode(',', $keywords)) < 5) {
                        $fail("Please enter atleast 5 $attribute.");
                    }
                },
            ],
        ]);

        $data = $request->only(['title','description','keywords']);
        $data['user_id'] = auth()->id();
        $news = NewsModel::create($data);

        if ($request->hasFile('image')){
            $file = $request->file('image');
            $customname = time() . '.' . $file->getClientOriginalExtension();
            $news->addMedia($file)
                    ->usingFileName($customname)
                    ->toMediaCollection('image');
        }

        return redirect()->route('news.index')->withStatus('Record saved successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\NewsModel  $news
     * @return \Illuminate\Http\Response
     */
    public function show(NewsModel $news)
    {
        //
    }

    /**
     * Change status the specified resource from storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\NewsModel  $news
     * @return \Illuminate\Http\Response
     */
    public function status(Request $request, NewsModel $news){
        if (isset($news->is_approved) && $news->is_approved==FALSE) {
            $news->update(['is_approved'=>TRUE]);
        }else{
            $news->update(['is_approved'=>FALSE]);
        }
        return redirect()->route('news.index')->withStatus('Record updated successfully.');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\NewsModel  $news
     * @return \Illuminate\Http\Response
     */
    public function edit(NewsModel $news)
    {
        return view('news.form',compact('news'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\NewsModel  $news
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, NewsModel $news)
    {
        $request->validate([
            'title' => 'required|unique:news,title,'.$news->id,
            'description' => 'required',
            'image'=>[
                'file',
                'image',
                'max:'.(config('media-library.max_file_size') / 1024),
            ],
            'keywords' => [
                'required',
                function ($attribute, $keywords, $fail) {
                    if (count(explode(',', $keywords)) < 5) {
                        $fail("Please enter at least 5 $attribute.");
                    }
                },
            ],
        ]);

        $data = $request->only(['title','description','keywords']);
        $news->update($data);

        if ($request->hasFile('image')){
            $file = $request->file('image');
            $customname = time() . '.' . $file->getClientOriginalExtension();
            $news->addMedia($file)
                    ->usingFileName($customname)
                    ->toMediaCollection('image');
        }

        return redirect()->route('news.index')->withStatus('Record updated successfully.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\NewsModel  $news
     * @return \Illuminate\Http\Response
     */
    public function destroy(NewsModel $news)
    {
        $news->delete();
        return redirect()->route('news.index')->withStatus('Record deleted successfully.');
    }
}

resources/views/news/form.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header">{{ __('Add News') }}</div>

                <div class="card-body">
                    <form method="POST" action="{{ isset($news->id)?route('news.update',$news->id):route('news.store') }}" id="frmNews" enctype="multipart/form-data">
                        @csrf
                        @if(isset($news->id))
                        @method('PUT')
                        @endif

                        <div class="form-group row">
                            <label for="title" class="col-md-2 col-form-label text-md-right">{{ __('Title') }}</label>

                            <div class="col-md-8">
                                <input id="title" type="text" class="form-control @error('title') is-invalid @enderror" name="title" value="{{ old('title', isset($news->title)?$news->title:'') }}" required autocomplete="title" autofocus>

                                @error('title')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="description" class="col-md-2 col-form-label text-md-right">{{ __('Description') }}</label>

                            <div class="col-md-8">
                                <textarea id="description" type="text" class="form-control @error('description') is-invalid @enderror" name="description" rows="10" required>{{ old('description', isset($news->description)?$news->description:'') }}</textarea>

                                @error('description')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        @if(isset($news) && $news->getMedia('image')->count() > 0 && file_exists($news->getFirstMedia('image')->getPath()))
                        <div class="form-group row">
                            <label for="image" class="col-md-2 col-form-label text-md-right">&nbsp;</label>
                            <div class="col-md-2">
                                <img class="img-fluid" src="{{ $news->getFirstMedia('image')->getFullUrl() }}">
                            </div>
                        </div>
                        @endif

                        <div class="form-group row">
                            <label for="image" class="col-md-2 col-form-label text-md-right">{{ __('Image') }}</label>

                            <div class="col-md-8">
                                <input id="image" type="file" class="@error('image') is-invalid @enderror" name="image" value="">

                                @error('image')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="keywords" class="col-md-2 col-form-label text-md-right">{{ __('Keywords') }}</label>

                            <div class="col-md-8">
                                <input id="keywords" type="text" class="form-control @error('keywords') is-invalid @enderror" name="keywords" value="{{ old('keywords', isset($news->keywords)?$news->keywords:'') }}"  data-role="tagsinput" required>

                                @error('keywords')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-2">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Submit') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('styles')
<link rel="stylesheet" type="text/css" href="{{ asset('js/bootstrap-tagsinput/dist/bootstrap-tagsinput.css') }}">
<style type="text/css">
.bootstrap-tagsinput {
    width: 100%;
}
</style>
@endsection

@section('scripts')
<script src="{{ asset('js/jquery-validation/dist/jquery.validate.min.js') }}"></script>
<script src="{{ asset('js/bootstrap-tagsinput/dist/bootstrap-tagsinput.min.js') }}"></script>
<script type="text/javascript">
jQuery(document).ready(function(){
    jQuery('#keywords').tagsinput();

    jQuery('.bootstrap-tagsinput input').keydown(function( event ) {
        if ( event.which == 13 ) {
            jQuery(this).blur();
            jQuery(this).focus();
            return false;
        }
    });

    jQuery.validator.addMethod("minTagsInput", function(value, element) {
        return $(element).tagsinput('items').length >= 5;
    }, "Please enter at least 5 keywords.");

    jQuery('#frmNews').validate({
        rules: {
            title: {
                required: true,
            },
            description: {
                required: true,
            },
            keywords: {
                required: true,
                minTagsInput: true
            }
        }
    });
});
</script>
@endsection

resources/views/news/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    @role(config('constants.ROLE_TYPE_USER'))
                    <a href="{{ route('news.create') }}" class="btn btn-primary float-right">Add</a>
                    @endrole
                    {{ __('News') }}
                </div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    <table class="table" id="news">
                        <thead>
                            <tr>
                                <th>Created At</th>
                                @role(config('constants.ROLE_TYPE_SUPERADMIN'))
                                <th>User</th>
                                @endrole
                                <th>Title</th>
                                <th>Keywords</th>
                                <th>Approved</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('styles')
<link href="{{ asset('js/datatables/dataTables.bootstrap4.min.css') }}" rel="stylesheet">
@endsection

@section('scripts')
<script src="{{ asset('js/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('js/datatables/dataTables.bootstrap4.min.js') }}"></script>
<script type="text/javascript">
jQuery(document).ready(function(){
    getNews();
});
 
function getNews(){
    jQuery('#news').dataTable().fnDestroy();
    jQuery('#news tbody').empty();
    jQuery('#news').DataTable({
        processing: false,
        serverSide: true,
        ajax: {
            url: '{{ route("news.getNews") }}',
            method: 'POST'
        },
        columns: [
            {data: 'created_at', name: 'created_at'},
            @role(config('constants.ROLE_TYPE_SUPERADMIN'))
            {data: 'user.name', name: 'user.name'},
            @endrole
            {data: 'title', name: 'title'},
            {data: 'keywords', name: 'keywords'},
            {data: 'is_approved', name: 'is_approved', class: 'text-center'},
            {data: 'actions', name: 'actions', orderable: false, searchable: false},
        ],
        order: [[0, 'asc']]
    });
}
</script>
@endsection